/* GENERATED by bin/fetch-pool-info.mjs from the pool directory at
 * https://sundlaugar.is — do not edit by hand. Run it and diff it.
 *
 * What each pool's page on the directory says a swimmer needs: where it is, how
 * to reach it, what it has, when it is open and what it costs. Not the
 * directory's descriptions or photographs — the page links to those. See the
 * script for how each field is read, and README.md for how the page uses it.
 *
 * `fetched` is the day each pool was read. Hours and prices change, and the
 * page says how old they are rather than presenting them as today's.
 */

export const POOL_INFO = [
  {
    "id": "alftaneslaug",
    "name": "Álftaneslaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/alftaneslaug/",
    "fetched": "2026-09-16",
    "address": "Breiðumýri, 225 Álftanes",
    "phone": "550 2350",
    "email": "gardabaer@gardabaer.is",
    "web": "http://www.gardabaer.is/thjonusta-i-gardabae/ithrottir/sundlaugar-gardabaejar/alftaneslaug/",
    "facebook": null,
    "instagram": null,
    "longest": 25,
    "facilities": ["outdoor","indoor","hotTubs","sauna","slide","kids","gym","accessible"],
    "hours": [
      {
        "kind": "open",
        "title": "Frá 1. júní til 30. september",
        "season": {"from":"06-01","to":"09-30"},
        "rows": [
          {"label":"Mánudaga til föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugardaga","days":[6],"closed":false,"times":["09:00–18:00"],"extra":null},
          {"label":"Sunnudaga","days":[0],"closed":false,"times":["09:00–22:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "open",
        "title": "Vetraropnun",
        "season": {"from":"10-01","to":"05-31"},
        "rows": [
          {"label":"Mánudaga til föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugardaga og sunnudaga","days":[0,6],"closed":false,"times":["08:00–18:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "other",
        "title": "Opnunartími Gym – heilsu",
        "season": null,
        "rows": [
          {"label":"Virka daga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Helgar","days":[0,6],"closed":false,"times":["09:00–18:00"],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar","30 miðar","6 mánaða kort","Árskort"],
          "rows": [
            ["Börn, 0 - 17 ára","0 kr","","","",""],
            ["Fullorðnir","1.350 kr","6.000 kr","12.400 kr","27.600 kr","49.000 kr"],
            ["67 ára og eldri","0 kr","","","",""]
          ]
        },
        {"head":["Sundföt","Handklæði"],"rows":[["Leiga","800 kr","800 kr"],["CTS-kort \"Garðakortið\"","1.250 kr",""]]}
      ]
    },
    "priceNotes": [
      "Varðandi aðra þætti gjaldskyldu:",
      "Börn 0-18 ára eru ekki gjaldskyld, miðað er við daginn sem þau verða 18 ára",
      "Gjaldskylda fellur niður við 67 ára aldur miðað við afmælisdag, framvísa verður persónuskilríkjum og kaupa rafrænt Garðakort.",
      "Öryrkjar eru ekki gjaldskyldir gegn framvísun skírteinis frá Sjálfsbjörgu, félagi fatlaðra í Reykjavík, sem skal endurnýjað árlega.",
      "Skírteini TR, grænt vegna varanlegrar örorku, gult vegna tímabundinnar örorku og blátt skírteini Blindrafélagsins, gefa einnig gjaldfrjálsan aðgang.",
      "Allir sem eru með gjaldfrían aðgang verða að vera með Garðakortið til að hlaða inn aðgangsheimild. Þannig getur hver og einn afgreitt sig sjálfur.",
      "Annað:",
      "Hætt er að selja aðgang hálfri klukkustund fyrir lokun. Börnum yngri en 10 ára er óheimill aðgangur að sundstöðum nema í fylgd með syndum einstaklingi 15 ára eða eldri. Frá 1. júní ár hvert geta börn sem verða 10 ára á árinu farið í sund án fylgdarmanns (eftir 4. bekk) enda séu þau orðin synd.",
      "GYM – Heilsa",
      "*Innan 30 daga frá því það fellur úr gildi",
      "Öll kortin gilda í heilsurækt og sund í Álftaneslaug. Hægt er að nota aðrar GYM heilsu stöðvar utan Garðabæjar gegn greiðslu aðgangseyris í sund á viðkomandi stað.",
      "Allir meðlimir geta hringt og pantað sér ókeypis tíma með þjálfara. Í tímanum er kennt á tækin og sérsniðin æfingaáætlun útbúin."
    ]
  },
  {
    "id": "arbaejarlaug",
    "name": "Árbæjarlaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/190-2/",
    "fetched": "2026-09-16",
    "address": "Fylkisvegur 9, 110 Reykjavík",
    "phone": "411 5200",
    "email": "upplysingar@reykjavik.is",
    "web": "http://reykjavik.is/stadir/arbaejarlaug",
    "facebook": null,
    "instagram": null,
    "longest": 25,
    "facilities": ["outdoor","indoor","hotTubs","sauna","kids","accessible","aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugar- og sunnudaga","days":[0,6],"closed":false,"times":["09:00–21:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "aqua",
        "title": "Sundleikfimi er í boði",
        "season": null,
        "rows": [
          {"label":"Þriðjudaga","days":[2],"closed":false,"times":["08:30"],"extra":"(inni)"},
          {"label":"Þriðjudaga","days":[2],"closed":false,"times":["09:30"],"extra":"(úti)"},
          {"label":"Fimmtudaga","days":[4],"closed":false,"times":["08:30"],"extra":"(inni)"},
          {"label":"Fimmtudaga","days":[4],"closed":false,"times":["09:30"],"extra":"(úti)"}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar**","Árskort***"],
          "rows": [
            ["Börn, 0 - 9 ára","0 kr","",""],
            ["Börn, 10 - 17 ára","400 kr *","1.450 kr","2.000 kr"],
            ["Fullorðnir","1.500 kr","7.000 kr","34.000 kr"],
            ["67 ára og eldri","","","4.000 kr"],
            ["Handhafar TR - Örorkuskírteinis","0 kr","",""]
          ]
        },
        {
          "head": ["Sundföt","Handklæði"],
          "rows": [["Leiga","1.270 kr","860 kr"],["Sund, handklæði og sundföt","2.770 kr",""]]
        },
        {"head":[],"rows":[["Útg. á rafr. handhafakorti","1.000 kr"],["Brautarleiga v. kennslu","8.150 kr"]]}
      ]
    },
    "priceNotes": [
      "* Börn byrja að greiða 1. ágúst árið sem þau verða 10 ára.",
      "** Inneign 10 skipta korta gildir í 4 ár frá kaupum – skiptakort gilda ekki fyrir hópa.",
      "*** 12 mánaðar binding, mánaðargjald er 2.833 kr pr fullorðin og 333 kr fyrir 67 ára og eldri.",
      "Þar sem Reykjavíkurkortið er aðgangskort er framvísun kortsins nauðsynleg til notkunar. Ekki er mögulegt að óska eftir aðgangi með öllum leiðum, s.s. uppflettingu á kennitölu í afgreiðslu nema gegn framvísan löggildra skilríkja. Aðgangskort er forsenda virkni áskrifta/inneigna.",
      "Umönnunaraðili barna fær frítt með gegn framvísun umönnunarskírteinis frá TR."
    ]
  },
  {
    "id": "asgardslaug",
    "name": "Ásgarðslaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/asgardslaug-2/",
    "fetched": "2026-09-16",
    "address": "Íþróttamiðstöðinni Ásgarði",
    "phone": "565 8066",
    "email": "karijo@gardabaer.is",
    "web": "http://www.gardabaer.is/thjonusta-i-gardabae/ithrottir/sundlaugar-gardabaejar/asgardslaug/",
    "facebook": null,
    "instagram": null,
    "longest": null,
    "facilities": ["outdoor","hotTubs","coldTub","slide","kids","accessible"],
    "hours": [
      {
        "kind": "open",
        "title": "Frá 1. júní til 30. september",
        "season": {"from":"06-01","to":"09-30"},
        "rows": [
          {"label":"Mánudaga til föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugardaga","days":[6],"closed":false,"times":["08:00–18:00"],"extra":null},
          {"label":"Sunnudaga","days":[0],"closed":false,"times":["08:00–22:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "open",
        "title": "Vetraropnun",
        "season": {"from":"10-01","to":"05-31"},
        "rows": [
          {"label":"Mánudaga til föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugardaga og sunnudaga","days":[0,6],"closed":false,"times":["08:00–18:00"],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar","30 miðar","6 mánaða","Árskort"],
          "rows": [
            ["Börn, 0 - 17 ára","0 kr","","","",""],
            ["Fullorðnir","1.350 kr","6.000 kr","12.400 kr","27.600 kr","49.000 kr"],
            ["67 ára og eldri","0 kr","","","",""]
          ]
        },
        {"head":["Sundföt","Handklæði"],"rows":[["Leiga","800 kr","800 kr"],["CTS-kort \"Garðakortið\"","1.250 kr",""]]}
      ]
    },
    "priceNotes": [
      "Varðandi aðra þætti gjaldskyldu:",
      "Börn 0-17 ára eru ekki gjaldskyld, miðað er við daginn sem þau verða 18 ára",
      "Gjaldskylda fellur niður við 67 ára aldur miðað við afmælisdag, framvísa verður persónuskilríkjum og kaupa rafrænt Garðakort.",
      "Öryrkjar eru ekki gjaldskyldir gegn framvísun skírteinis sem gefið er út af Sjálfsbjörgu, félagi fatlaðra í Reykjavík, sem skal endurnýjað árlega.",
      "Skírteini Tryggingastofnunar ríkisins, grænt vegna varanlegrar örorku, gult vegna tímabundinnar örorku og blátt skírteini Blindrafélagsins, gefa einnig gjaldfrjálsan aðgang.",
      "Allir sem eru með gjaldfrían aðgang verða að vera með Garðakortið til að hlaða inn aðgangsheimild. Þannig getur hver og einn afgreitt sig sjálfur.",
      "Annað:",
      "Hætt er að selja aðgang hálfri klukkustund fyrir lokun. Börnum yngri en 10 ára er óheimill aðgangur að sundstöðum nema í fylgd með syndum einstaklingi 15 ára eða eldri. Frá 1. júní ár hvert geta börn sem verða 10 ára á árinu farið í sund án fylgdarmanns (eftir 4. bekk) enda séu þau orðin synd."
    ]
  },
  {
    "id": "asvallalaug",
    "name": "Ásvallalaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/asvallalaug-2/",
    "fetched": "2026-09-16",
    "address": "Ásvöllum 2, 221 Hafnarfirði",
    "phone": "512 4050",
    "email": "sundstadir@hafnarfjordur.is",
    "web": "http://www.hafnarfjordur.is/ibuar/ithrottir-og-utivera/sundlaugar/asvallalaug/asvallalaug",
    "facebook": null,
    "instagram": null,
    "longest": 50,
    "facilities": ["indoor","hotTubs","steam","slide","kids","gym","accessible","aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – fimmtudaga","days":[1,2,3,4],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Föstudaga","days":[5],"closed":false,"times":["06:30–20:00"],"extra":null},
          {"label":"Laugardaga","days":[6],"closed":false,"times":["08:00–18:00"],"extra":null},
          {"label":"Sunnudaga","days":[0],"closed":false,"times":["08:00–17:00"],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar","30 miðar","6 mán kort","Árskort"],
          "rows": [
            ["Börn, 0 - 17 ára","0 kr","","","",""],
            ["Fullorðnir","1.250 kr","5.200 kr","14.000 kr","20.500 kr","36.400 kr"],
            ["Aldraðir og öryrkjar","0","","","",""]
          ]
        },
        {"head":["Sundföt","Handklæði","Sundf. & handkl."],"rows":[["Leiga","940 kr","940 kr","1.450 kr"]]}
      ]
    },
    "priceNotes": []
  },
  {
    "id": "breidholtslaug",
    "name": "Breiðholtslaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/breidholtslaug-2/",
    "fetched": "2026-09-16",
    "address": "Austurberg 3, 111 Reykjavík",
    "phone": "411 5250",
    "email": "upplysingar@reykjavik.is",
    "web": "http://reykjavik.is/stadir/breidholtslaug",
    "facebook": null,
    "instagram": null,
    "longest": 25,
    "facilities": ["outdoor","indoor","hotTubs","coldTub","steam","sauna","slide","kids","massage","accessible","aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugar- og sunnudaga","days":[0,6],"closed":false,"times":["09:00–22:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "aqua",
        "title": "Sundleikfimi er í boði",
        "season": null,
        "rows": [
          {"label":"Mánudaga","days":[1],"closed":false,"times":["09:50"],"extra":"(úti)"},
          {"label":"Miðvikudaga","days":[3],"closed":false,"times":["09:30"],"extra":"(úti)"}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar**","Árskort***"],
          "rows": [
            ["Börn, 0 - 9 ára","0 kr","",""],
            ["Börn, 10 - 17 ára","400 kr *","1.450 kr","2.000 kr"],
            ["Fullorðnir","1.500 kr","7.000 kr","34.000 kr"],
            ["67 ára og eldri","","","4.000 kr"],
            ["Handhafar TR – Örorkuskírteinis","0 kr","",""]
          ]
        },
        {
          "head": ["Sundföt","Handklæði"],
          "rows": [["Leiga","1.270 kr","860 kr"],["Sund, handklæði og sundföt","2.700 kr",""]]
        },
        {"head":[],"rows":[["útg. á rafr. handhafakorti","1.000 kr"],["Brautarleiga v. kennslu","8.150 kr"]]}
      ]
    },
    "priceNotes": [
      "* Börn byrja að greiða 1. ágúst árið sem þau verða 10 ára.",
      "** Inneign 10 skipta korta gildir í 4 ár frá kaupum – skiptakort gilda ekki fyrir hópa.",
      "*** 12 mánaðar binding, mánaðargjald er 2.833 kr pr fullorðin og 333 kr fyrir 67 ára og eldri.",
      "Þar sem Reykjavíkurkortið er aðgangskort er framvísun kortsins nauðsynleg til notkunar. Ekki er mögulegt að óska eftir aðgangi með öllum leiðum, s.s. uppflettingu á kennitölu í afgreiðslu nema gegn framvísan löggildra skilríkja. Aðgangskort er forsenda virkni áskrifta/inneigna.",
      "Umönnunaraðili barna fær frítt með gegn framvísun umönnunarskírteinis frá TR."
    ]
  },
  {
    "id": "dalslaug",
    "name": "Dalslaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/dalslaug/",
    "fetched": "2026-09-16",
    "address": "Úlfarsbraut 128 113 Reykjavík",
    "phone": "411 5650",
    "email": "upplysingar@reykjavik.is",
    "web": "https://reykjavik.is/dalslaug",
    "facebook": null,
    "instagram": null,
    "longest": 25,
    "facilities": ["outdoor","indoor","hotTubs","coldTub","steam","kids"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Virkir dagar","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Helgar","days":[0,6],"closed":false,"times":["09:00–22:00"],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar **","Árskort ***"],
          "rows": [
            ["Börn, 0 - 9 ára","0 kr","",""],
            ["Börn, 10 - 17 ára","400 kr *","1.450 kr","2.000 kr"],
            ["Fullorðnir","1.500 kr","7.000 kr","34.000 kr"],
            ["67 ára og eldri","","","4.000 kr"],
            ["Handhafar TR – Örorkuskírteinis","0 kr","",""]
          ]
        },
        {
          "head": ["Sundföt","Handklæði"],
          "rows": [["Leiga","1.270 kr","860 kr"],["Sund, handkl. og sundföt","2.700 kr",""]]
        },
        {"head":[],"rows":[["Útg. á rafrænu handhafakorti","1.000 kr"],["Brautarleiga v. kennslu","8.150 kr"]]}
      ]
    },
    "priceNotes": [
      "* Börn byrja að greiða 1. ágúst árið sem þau verða 10 ára.",
      "** Inneign 10 skipta korta gildir í 4 ár frá kaupum – skiptakort gilda ekki fyrir hópa.",
      "*** 12 mánaðar binding, mánaðargjald er 2.833 kr pr fullorðin og 333 kr fyrir 67 ára og eldri.",
      "Þar sem Reykjavíkurkortið er aðgangskort er framvísun kortsins nauðsynleg til notkunar. Ekki er mögulegt að óska eftir aðgangi með öllum leiðum, s.s. uppflettingu á kennitölu í afgreiðslu nema gegn framvísan löggildra skilríkja. Aðgangskort er forsenda virkni áskrifta/inneigna.",
      "Umönnunaraðili barna fær frítt með gegn framvísun umönnunarskírteinis frá TR."
    ]
  },
  {
    "id": "grafarvogslaug",
    "name": "Grafarvogslaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/grafarvogslaug-2/",
    "fetched": "2026-09-16",
    "address": "Dalhúsum 2, 112 Reykjavík",
    "phone": "411 5300",
    "email": "upplysingar@reykjavik.is",
    "web": "http://reykjavik.is/stadir/grafarvogslaug",
    "facebook": null,
    "instagram": null,
    "longest": null,
    "facilities": ["outdoor","indoor","hotTubs","sauna","slide","kids","accessible","aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugar- og sunnudaga","days":[0,6],"closed":false,"times":["09:00–22:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "aqua",
        "title": "Sundleikfimi er í boði",
        "season": null,
        "rows": [
          {"label":"Þriðjudaga","days":[2],"closed":false,"times":["14:00"],"extra":"(inni)"},
          {"label":"Fimmtudaga","days":[4],"closed":false,"times":["14:00"],"extra":"(inni)"}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar**","Árskort**"],
          "rows": [
            ["Börn, 0 - 9 ára","0 kr","",""],
            ["Börn, 10 - 17 ára","400 kr *","1.450 kr **","2.000 kr"],
            ["Fullorðnir","1.500 kr","7.000 kr **","34.000 kr"],
            ["67 ára og eldri","","","4.000 kr"],
            ["Handhafar TR – Örorkuskírteinis","0 kr","",""]
          ]
        },
        {
          "head": ["Sundföt","Handklæði"],
          "rows": [["Leiga","1.270 kr","860 kr"],["Sund, handklæði og sundföt","2.700 kr",""]]
        },
        {"head":[],"rows":[["Útg. á rafr. handhafakorti","1.000 kr"],["Brautarleiga v. kennslu","8.150 kr"]]}
      ]
    },
    "priceNotes": [
      "* Börn byrja að greiða 1. ágúst árið sem þau verða 10 ára.",
      "** Inneign 10 skipta korta gildir í 4 ár frá kaupum – skiptakort gilda ekki fyrir hópa.",
      "*** 12 mánaðar binding, mánaðargjald er 2.833 kr pr fullorðin og 333 kr fyrir 67 ára og eldri.",
      "Þar sem Reykjavíkurkortið er aðgangskort er framvísun kortsins nauðsynleg til notkunar. Ekki er mögulegt að óska eftir aðgangi með öllum leiðum, s.s. uppflettingu á kennitölu í afgreiðslu nema gegn framvísan löggildra skilríkja. Aðgangskort er forsenda virkni áskrifta/inneigna.",
      "Umönnunaraðili barna fær frítt með gegn framvísun umönnunarskírteinis frá TR."
    ]
  },
  {
    "id": "klebergslaug",
    "name": "Klébergslaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/klebergslaug/",
    "fetched": "2026-09-16",
    "address": "Kollagrund 4, 116 Reykjavík",
    "phone": "411 5660",
    "email": "upplysingar@reykjavik.is",
    "web": null,
    "facebook": "https://www.facebook.com/Klebergslaug/",
    "instagram": null,
    "longest": null,
    "facilities": ["aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Opnunartími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – fimmtudaga","days":[1,2,3,4],"closed":false,"times":["09:00–22:00"],"extra":null},
          {"label":"Föstudaga","days":[5],"closed":false,"times":["09:00–19:00"],"extra":null},
          {"label":"Laugardaga","days":[6],"closed":false,"times":["11:00–18:00"],"extra":null},
          {"label":"Sunnudaga","days":[0],"closed":false,"times":["11:00–22:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "aqua",
        "title": "Sundleikfimi",
        "season": null,
        "rows": [{"label":"Miðvikudaga","days":[3],"closed":false,"times":["14:00"],"extra":"(úti)"}],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar**","Árskort***"],
          "rows": [
            ["Börn, 0 - 9 ára","0 kr","",""],
            ["Ungmenni, 10 - 17 ára","400 kr *","1.450 kr","2.000 kr"],
            ["Fullorðnir","1.500 kr","7.000 kr","34.000 kr"],
            ["67 ára og eldri","","","4.000 kr"],
            ["Handhafar TR – Örorkuskírteinis","0 kr","",""]
          ]
        },
        {
          "head": ["Sundföt","Handklæði"],
          "rows": [["Leiga","1.270 kr","860 kr"],["Sund, handklæði og sundföt","2.700 kr",""]]
        },
        {
          "head": ["Fullorðnir"],
          "rows": [["útg. á rafr. handhafakorti","1.000 kr"],["Brautarleiga v. kennslu.","8.150 kr"]]
        }
      ]
    },
    "priceNotes": [
      "* Börn byrja að greiða 1. ágúst árið sem þau verða 10 ára.",
      "** Inneign 10 skipta korta gildir í 4 ár frá kaupum – skiptakort gilda ekki fyrir hópa.",
      "*** 12 mánaðar binding, mánaðargjald er 2.833 kr pr fullorðin og 333 kr fyrir 67 ára og eldri.",
      "Þar sem Reykjavíkurkortið er aðgangskort er framvísun kortsins nauðsynleg til notkunar. Ekki er mögulegt að óska eftir aðgangi með öllum leiðum, s.s. uppflettingu á kennitölu í afgreiðslu nema gegn framvísan löggildra skilríkja. Aðgangskort er forsenda virkni áskrifta/inneigna.",
      "Umönnunaraðili barna fær frítt með gegn framvísun umönnunarskírteinis frá TR."
    ]
  },
  {
    "id": "sundlaug-kopavogs",
    "name": "Kópavogslaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/sundlaug-kopavogs-2/",
    "fetched": "2026-09-16",
    "address": "Borgarholtsbraut 17, 200 Kópavogur",
    "phone": "441 8500",
    "email": "jakob@kopavogur.is",
    "web": "http://www.kopavogur.is/is/mannlif/utivist/sundlaugar-i-kopavogi/sundlaug-kopavogs",
    "facebook": "https://www.facebook.com/pages/Sundlaug-K%C3%B3pavogs/208306422529235?fref=ts",
    "instagram": null,
    "longest": 50,
    "facilities": ["outdoor","indoor","hotTubs","steam","slide","kids","massage","gym","aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Sumaropnun 1. maí til 30. september",
        "season": {"from":"05-01","to":"09-30"},
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugar- og sunnudaga","days":[0,6],"closed":false,"times":["08:00–20:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "open",
        "title": "Vetraropnun, 1. október til 30. apríl",
        "season": {"from":"10-01","to":"04-30"},
        "rows": [
          {"label":"Virka daga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugar – og sunnudaga","days":[0,6],"closed":false,"times":["08:00–18:00"],"extra":null}
        ],
        "notes": [
          {
            "text": "Frí vatnsleikfimi þriðjudaga, miðvikudaga og föstudaga kl 09:30 – 10:15. Lögð áhersla á aukið þol, styrk og liðleika. Þjálfari er Helga Guðrún Gunnarsdóttir íþrótta – og heilsufræðingur frá HÍ."
          }
        ]
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar","30 miðar","60 miðar","Árskort"],
          "rows": [
            ["Börn, 0 - 17 ára","0 kr","","","",""],
            ["Fullorðnir, 18 - 66 ára","1.280 kr","7.300 kr","15.000 kr","24.200 kr","36.500 kr"],
            ["Eldri borgarar","0 kr","","","",""]
          ]
        },
        {"head":["Sundföt","Handklæði"],"rows":[["Leiga","730 kr","730 kr"]]}
      ]
    },
    "priceNotes": ["Punktakort eru handhafakort."]
  },
  {
    "id": "laugardalslaug",
    "name": "Laugardalslaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/laugardalslaug/",
    "fetched": "2026-09-16",
    "address": "v/ Sundlaugarveg, 105 Reykjavík",
    "phone": "411 5100",
    "email": "upplysingar@reykjavik.is",
    "web": "http://reykjavik.is/stadir/laugardalslaug",
    "facebook": "https://www.facebook.com/pages/Laugardalslaug/189977011039980?fref=ts",
    "instagram": null,
    "longest": 50,
    "facilities": ["outdoor","indoor","hotTubs","steam","sauna","slide","kids","massage","food","accessible","aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – Föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Helgar","days":[0,6],"closed":false,"times":["08:00–22:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "aqua",
        "title": "Sundleikfimi er í boði",
        "season": null,
        "rows": [
          {"label":"Mánudaga","days":[1],"closed":false,"times":["08:45"],"extra":null},
          {"label":"Þriðjudaga","days":[2],"closed":false,"times":["09:30"],"extra":null},
          {"label":"Miðvikudaga","days":[3],"closed":false,"times":["08:45"],"extra":null},
          {"label":"Fimmtudaga","days":[4],"closed":false,"times":["09:30"],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar**","Árskort***"],
          "rows": [
            ["Börn, 0 - 9 ára","0 kr","",""],
            ["Ungmenni, 10 - 17 ára","400 kr *","1.450 kr","2.000 kr"],
            ["Fullorðnir","1.500 kr","7.000 kr","34.000 kr"],
            ["67 ára og eldri","","","4.000 kr"],
            ["Handhafar TR – Örorkuskírteinis","0 kr","",""]
          ]
        },
        {
          "head": ["Sundföt","Handklæði"],
          "rows": [["Leiga","1.270 kr","860 kr"],["Sund, handklæði og sundföt","2.700 kr",""]]
        },
        {"head":[],"rows":[["Útg. á rafr handhafakorti","1.000 kr"],["Brautarleiga v. kennslu","8.150 kr"]]}
      ]
    },
    "priceNotes": [
      "* Börn byrja að greiða 1. ágúst árið sem þau verða 10 ára.",
      "** Inneign 10 skipta korta gildir í 4 ár frá kaupum – skiptakort gilda ekki fyrir hópa.",
      "*** 12 mánaðar binding, mánaðargjald er 2.833 kr pr fullorðin og 333 kr fyrir 67 ára og eldri.",
      "Þar sem Reykjavíkurkortið er aðgangskort er framvísun kortsins nauðsynleg til notkunar. Ekki er mögulegt að óska eftir aðgangi með öllum leiðum, s.s. uppflettingu á kennitölu í afgreiðslu nema gegn framvísan löggildra skilríkja. Aðgangskort er forsenda virkni áskrifta/inneigna.",
      "Umönnunaraðili barna fær frítt með gegn framvísun umönnunarskírteinis frá TR."
    ]
  },
  {
    "id": "lagafellslaug",
    "name": "Lágafellslaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/lagafellslaug-2/",
    "fetched": "2026-09-16",
    "address": "Lækjarhlíð 1a, 270 Mosfellsbær",
    "phone": "517 6080",
    "email": "gretarg@mos.is",
    "web": "http://www.mosfellsbaer.is/thjonusta/ithrotta-og-tomstundastarf/ithrottamidstodvar/",
    "facebook": "https://www.facebook.com/pages/L%C3%A1gafellslaug/218121901547549?fref=ts",
    "instagram": null,
    "longest": 25,
    "facilities": ["indoor","hotTubs","steam","sauna","slide","kids","massage"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugar- og sunnudaga","days":[0,6],"closed":false,"times":["08:00–19:00"],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar","Árskort"],
          "rows": [
            ["Börn, 0 - 17 ára","0 kr","",""],
            ["Fullorðnir","1.300 kr","5.850 kr","44.500 kr"],
            ["Aldraðir og öryrkjar","0 kr","",""]
          ]
        },
        {"head":["Sundföt","Handklæði"],"rows":[["Leiga","1.100 kr","1.100 kr"],["Áfyllingakort Mos kort","850 kr",""]]},
        {"head":[],"rows":[["Stór salur","11.800 kr"],["Gervigrasvöllur","21.900 kr"]]}
      ]
    },
    "priceNotes": [
      "Varðandi aðra þætti gjaldskyldu",
      "– Gjaldskylda fellur niður við 67 ára aldur og miðast við afmælisdag, framvísa verður persónuskírteini.",
      "– Öryrkjar eru ekki gjaldskyldir gegn framvísun skírteinis gefið út af Sjálfsbjörgu, félagi fatlaðra í Reykjavík, sem skal endurnýjað árlega.",
      "– Einnig eru þeir ekki gjaldskyldir sem framvísa skírteini Tryggingastofnunar ríkisins “grænu skírteini” vegna varanlegrar örorku, skírteini Blindrafélags “bláu skírteini” og umönnunarkorti „gulu skírteini“ vegna sérstakrar umönnunar barns.",
      "Börn byrja að greiða 1. júní árið sem að þau verða 10 ára.",
      "Börn þurfa að vera orðin 10 ára til að fá að fara í sund ein án fylgdarmanns. ( Miðað er við 1. júní s.k. reglugerð þar um).",
      "Börn og unglingar 10 – 15 ára í grunnskólum Mosfellsbæjar geta í afgreiðslu sundlaugar sótt um endurgjaldslausan aðgan að sundlaugum með áfyllingu á Moskort sem kostar kr. 800. Gildistími korts er til 31. desember en þó ekki lengur en barn er í grunnskóla.",
      "Gildistími áfyllinga á Moskort er 2 ár."
    ]
  },
  {
    "id": "salalaug",
    "name": "Salalaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/salalaug/",
    "fetched": "2026-09-16",
    "address": "Versalir 3, 201 Kópavogur",
    "phone": "441 8600",
    "email": "gudmundur.h@kopavogur.is",
    "web": "http://www.kopavogur.is/is/mannlif/utivist/sundlaugar-i-kopavogi/sundlaugin-versalir-salalaug",
    "facebook": "https://www.facebook.com/pages/Salalaug/444391658918629?fref=ts",
    "instagram": null,
    "longest": 25,
    "facilities": ["outdoor","indoor","hotTubs","sauna","slide","massage"],
    "hours": [
      {
        "kind": "open",
        "title": "Sumaropnun 1. maí til 30. september",
        "season": {"from":"05-01","to":"09-30"},
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugardaga","days":[6],"closed":false,"times":["08:00–20:00"],"extra":null},
          {"label":"Sunnudaga","days":[0],"closed":false,"times":["08:00–22:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "open",
        "title": "Vetraropnun, 1. október til 30. apríl",
        "season": {"from":"10-01","to":"04-30"},
        "rows": [
          {"label":"Virka daga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugar – og sunnudaga","days":[0,6],"closed":false,"times":["08:00–18:00"],"extra":null}
        ],
        "notes": [{"text":"Ath! Katla Fitness heilsuræktin er opin á sama tíma og sundlaugin."}]
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 punkta kort","30 punkta kort","60 punkta kort","Árskort"],
          "rows": [
            ["Börn, 0 - 17 ára","0 kr","","","",""],
            ["Fullorðnir","1.280 kr","7.300 kr","15.000 kr","24.200 kr","36.500 kr"],
            ["Aldraðir og öryrkjar","0 kr","","","",""]
          ]
        },
        {"head":["Sundföt","Handklæði"],"rows":[["Leiga","730 kr","730 kr"]]}
      ]
    },
    "priceNotes": ["Punktakort er handhafakort."]
  },
  {
    "id": "seltjarnarneslaug",
    "name": "Seltjarnarneslaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/seltjarnarneslaug-2/",
    "fetched": "2026-09-16",
    "address": "Suðurströnd, 170 Seltjarnarnes",
    "phone": "561 1551",
    "email": "postur@seltjarnarnes.is",
    "web": "http://www.seltjarnarnes.is/thjonusta/ithrottirogtomstundir/sundlaug/",
    "facebook": null,
    "instagram": null,
    "longest": 25,
    "facilities": ["hotTubs","steam","slide","kids","massage","accessible","aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Opnunartími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–21:00"],"extra":null},
          {"label":"Laugar- og sunnudaga","days":[0,6],"closed":false,"times":["09:00–18:00"],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 skipti","3ja mán kort","1/2 árs kort","Árskort"],
          "rows": [
            ["Börn, 0 - 18 ára","0 kr","","","",""],
            ["Fullorðnir","1.300 kr","6.400 kr","16.850 kr","24.050 kr","46.500 kr"]
          ]
        },
        {"head":["Sundföt","Handklæði"],"rows":[["Leiga","2.500 kr*","2.500 kr*"]]}
      ]
    },
    "priceNotes": ["*1.500 kr endurgreiddar við skil."]
  },
  {
    "id": "sky-lagoon",
    "name": "Sky Lagoon",
    "region": "hofudborgarsvaedid",
    "kind": "lagoon",
    "source": "https://sundlaugar.is/sundlaugasafn/sky-lagoon/",
    "fetched": "2026-09-16",
    "address": "Vesturvör 44",
    "phone": "527 6800",
    "email": "info@skylagoon.is",
    "web": "http://www.skylagoon.is",
    "facebook": "http://www.facebook.com/skylagooniceland",
    "instagram": null,
    "longest": null,
    "facilities": ["food"],
    "hours": [
      {
        "kind": "open",
        "title": "Vetur",
        "season": {"from":"10-21","to":"04-30"},
        "rows": [{"label":"Alla daga","days":[0,1,2,3,4,5,6],"closed":false,"times":["10:00–21:00"],"extra":null}],
        "notes": []
      },
      {
        "kind": "open",
        "title": "Vor",
        "season": {"from":"05-01","to":"06-20"},
        "rows": [{"label":"Alla daga","days":[0,1,2,3,4,5,6],"closed":false,"times":["10:00–22:00"],"extra":null}],
        "notes": []
      },
      {
        "kind": "open",
        "title": "Sumar",
        "season": {"from":"06-21","to":"08-20"},
        "rows": [{"label":"Alla daga","days":[0,1,2,3,4,5,6],"closed":false,"times":["08:00–23:00"],"extra":null}],
        "notes": []
      },
      {
        "kind": "open",
        "title": "Haust",
        "season": {"from":"08-21","to":"10-20"},
        "rows": [{"label":null,"days":null,"closed":false,"times":["09:00–22:00"],"extra":null}],
        "notes": [{"text":"Vinsamlegast athugið að gestir eru beðnir að yfirgefa lónið hálftíma fyrir almennan lokunartíma."}]
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Fullorðnir - Verð frá","Ungmenni - Verð frá"],
          "rows": [["Saman","13.990 kr","6.995 kr"],["Sér","16.990 kr","8.495 kr"]]
        }
      ]
    },
    "priceNotes": []
  },
  {
    "id": "sudurbaejarlaug",
    "name": "Suðurbæjarlaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/sudurbaejarlaug/",
    "fetched": "2026-09-16",
    "address": "Hringbraut 77, 220 Hafnarfjörður",
    "phone": "565 3080",
    "email": "sundstadir@hafnarfjordur.is",
    "web": "http://www.hafnarfjordur.is/ibuar/ithrottir-og-utivera/sundlaugar/sudurbaejarlaug/sudurbaejarlaug",
    "facebook": "https://www.facebook.com/pages/Su%C3%B0urb%C3%A6jarlaug/183116281751578",
    "instagram": null,
    "longest": 25,
    "facilities": ["outdoor","indoor","hotTubs","coldTub","sauna","slide","kids","gym","aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – fimmtudaga","days":[1,2,3,4],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Föstudaga","days":[5],"closed":false,"times":["06:30–20:00"],"extra":null},
          {"label":"Laugardaga","days":[6],"closed":false,"times":["08:00–18:00"],"extra":null},
          {"label":"Sunnudaga","days":[0],"closed":false,"times":["08:00–21:00"],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar","30 miðar","6 mán kort","Árskort"],
          "rows": [
            ["Börn, 0 - 17 ára","0 kr","","","",""],
            ["Fullorðnir","1.250 kr","5.200 kr","14.000 kr","20.500 kr","36.400 kr"],
            ["Aldraðir og öryrkjar","0 kr","","","",""]
          ]
        },
        {"head":["Sundföt","Handklæði","Sundf. & handkl."],"rows":[["Leiga","940 kr","940 kr","1.450 kr"]]}
      ]
    },
    "priceNotes": []
  },
  {
    "id": "sundholl-hafnarfjardar",
    "name": "Sundhöll Hafnarfjarðar",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/sundholl-hafnarfjardar/",
    "fetched": "2026-09-16",
    "address": "Herjólfsgötu 10, 220 Hafnarfirði",
    "phone": "555 0088",
    "email": "sundstadir@hafnarfjordur.is",
    "web": "http://www.hafnarfjordur.is/ibuar/ithrottir-og-utivera/sundlaugar/sundhollin/sundlaugar",
    "facebook": null,
    "instagram": null,
    "longest": 25,
    "facilities": ["indoor","hotTubs","coldTub","sauna","massage"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–21:00"],"extra":null},
          {"label":"Laugardagar","days":[6],"closed":true,"times":[],"extra":null},
          {"label":"Sunnudagar","days":[0],"closed":true,"times":[],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar","30 miðar","6 mán kort","Árskort"],
          "rows": [
            ["Börn, 0 - 17 ára","0 kr","","","",""],
            ["Fullorðnir","1.250 kr","5.200 kr","14.000 kr","20.500 kr","36.400 kr"],
            ["Aldraðir og öryrkjar","0 kr","","","",""]
          ]
        },
        {"head":["Sundföt","Handklæði","Sundf. & handkl."],"rows":[["Leiga","940 kr","940 kr","1.450 kr"]]}
      ]
    },
    "priceNotes": []
  },
  {
    "id": "sundholl-reykjavikur",
    "name": "Sundhöll Reykjavíkur",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/sundholl-reykjavikur-2/",
    "fetched": "2026-09-16",
    "address": "V. Barónsstíg, 101 Reykjavík",
    "phone": "411 5350",
    "email": "upplysingar@reykjavik.is",
    "web": "http://reykjavik.is/stadir/sundholl-reykjavikur",
    "facebook": "https://www.facebook.com/pages/Sundh%C3%B6ll-Reykjav%C3%ADkur/203190919704835?fref=ts",
    "instagram": null,
    "longest": 25,
    "facilities": ["outdoor","indoor","hotTubs","coldTub","sauna","kids","diving","accessible","aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugardaga og sunnudaga","days":[0,6],"closed":false,"times":["08:00–22:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "aqua",
        "title": "Sundleikfimi er í boði",
        "season": null,
        "rows": [{"label":"Mánudaga – fimmtudaga","days":[1,2,3,4],"closed":false,"times":["07:50"],"extra":"(inni)"}],
        "notes": [{"text":"Sundkennsla er í boði föstudaga kl 08:30 í innilaug."}]
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar**","Árskort ***"],
          "rows": [
            ["Börn, 0 - 9 ára","0 kr","",""],
            ["Ungmenni, 10 - 17 ára","400 kr *","1.450 kr","2.000 kr"],
            ["Fullorðnir","1.500 kr","7.000 kr","34.000 kr"],
            ["67 ára og eldri","","","4.000 kr"],
            ["Handhafar TR – Örorkuskírteinis","0 kr","",""]
          ]
        },
        {
          "head": ["Sundföt","Handklæði"],
          "rows": [["Leiga","1.270 kr","860 kr"],["Sund, handklæði og sundföt","2.700 kr",""]]
        },
        {"head":[],"rows":[["Útg. á rafr handhafakorti","1.000 kr"],["Brautarleiga v. kennslu","8.150 kr"]]}
      ]
    },
    "priceNotes": [
      "* Börn byrja að greiða 1. ágúst árið sem þau verða 10 ára.",
      "** Inneign 10 skipta korta gildir í 4 ár frá kaupum – skiptakort gilda ekki fyrir hópa.",
      "*** 12 mánaðar binding, mánaðargjald er 2.833 kr pr fullorðin og 333 kr fyrir 67 ára og eldri.",
      "Þar sem Reykjavíkurkortið er aðgangskort er framvísun kortsins nauðsynleg til notkunar. Ekki er mögulegt að óska eftir aðgangi með öllum leiðum, s.s. uppflettingu á kennitölu í afgreiðslu nema gegn framvísan löggildra skilríkja. Aðgangskort er forsenda virkni áskrifta/inneigna.",
      "Umönnunaraðili barna fær frítt með gegn framvísun umönnunarskírteinis frá TR."
    ]
  },
  {
    "id": "varmarlaug",
    "name": "Varmárlaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/varmarlaug-2/",
    "fetched": "2026-09-16",
    "address": "Skólabraut, 270 Mosfellsbæ",
    "phone": "566 6754",
    "email": "gretarg@mos.is",
    "web": null,
    "facebook": "https://www.facebook.com/varmarlaug/",
    "instagram": null,
    "longest": null,
    "facilities": ["hotTubs","coldTub","sauna","kids","massage"],
    "hours": [
      {
        "kind": "open",
        "title": "Sumaropnun, frá 7. júní",
        "season": {"from":"06-07","to":"08-23"},
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–21:30"],"extra":null},
          {"label":"Laugardaga","days":[6],"closed":false,"times":["08:00–17:00"],"extra":null},
          {"label":"Sunnudaga","days":[0],"closed":false,"times":["08:00–16:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "open",
        "title": "Vetraropnun, frá 24. ágúst",
        "season": {"from":"08-24","to":"06-06"},
        "rows": [
          {"label":"Virka daga","days":[1,2,3,4,5],"closed":false,"times":["06:30–08:00","15:00–21:30"],"extra":null},
          {"label":"Laugardaga","days":[6],"closed":false,"times":["09:00–17:00"],"extra":null},
          {"label":"Sunnudaga","days":[0],"closed":false,"times":["09:00–16:00"],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miða kort","Árskort"],
          "rows": [
            ["Börn, 0 - 17 ára","0 kr","",""],
            ["Fullorðnir","1.300 kr","5.850 lkr","44.500 kr"],
            ["Aldraðir og öryrkjar","0 kr","",""]
          ]
        },
        {"head":["Sundföt","Handklæði"],"rows":[["Leiga","1.100 kr","1.100 kr"],["Áfyllingakort Mos kort","850 kr",""]]},
        {"head":[],"rows":[["Stór salur","11.800 kr"]]}
      ]
    },
    "priceNotes": [
      "Varðandi aðra þætti gjaldskyldu",
      "– Gjaldskylda fellur niður við 67 ára aldur og miðast við afmælisdag, framvísa verður persónuskírteini.",
      "– Öryrkjar eru ekki gjaldskyldir gegn framvísun skírteinis gefið út af Sjálfsbjörgu, félagi fatlaðra í Reykjavík, sem skal endurnýjað árlega.",
      "– Einnig eru þeir ekki gjaldskyldir sem framvísa skírteini Tryggingastofnunar ríkisins “grænu skírteini” vegna varanlegrar örorku, skírteini Blindrafélags “bláu skírteini” og umönnunarkorti „gulu skírteini“ vegna sérstakrar umönnunar barns.",
      "Börn byrja að greiða 1. júní árið sem að þau verða 10 ára.",
      "Börn þurfa að vera orðin 10 ára til að fá að fara í sund ein án fylgdarmanns. ( Miðað er við 1. júní s.k. reglugerð þar um).",
      "Börn og unglingar 10 – 15 ára í grunnskólum Mosfellsbæjar geta í afgreiðslu sundlaugar sótt um endurgjaldslausan aðgan að sundlaugum með áfyllingu á Moskort sem kostar kr. 600. Gildistími korts er til 31. desember en þó ekki lengur en barn er í grunnskóla.",
      "Gildistími áfyllinga á Moskort er 2 ár."
    ]
  },
  {
    "id": "vesturbaejarlaug",
    "name": "Vesturbæjarlaug",
    "region": "hofudborgarsvaedid",
    "kind": "pool",
    "source": "https://sundlaugar.is/sundlaugasafn/vesturbaejarlaug-2/",
    "fetched": "2026-09-16",
    "address": "V. Hofsvallagötu, 101 Reykjavík",
    "phone": "411 5150",
    "email": "upplysingar@reykjavik.is",
    "web": null,
    "facebook": null,
    "instagram": null,
    "longest": null,
    "facilities": ["hotTubs","massage","aquaAerobics"],
    "hours": [
      {
        "kind": "open",
        "title": "Afgreiðslutími",
        "season": null,
        "rows": [
          {"label":"Mánudaga – föstudaga","days":[1,2,3,4,5],"closed":false,"times":["06:30–22:00"],"extra":null},
          {"label":"Laugardaga og sunnudaga","days":[0,6],"closed":false,"times":["09:00–22:00"],"extra":null}
        ],
        "notes": []
      },
      {
        "kind": "aqua",
        "title": "Sundleikfimi er í boði",
        "season": null,
        "rows": [{"label":"Þriðjudaga og fimmtudaga","days":[2,4],"closed":false,"times":["10:45"],"extra":"(úti)"}],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt gjald","10 miðar**","Árskort***"],
          "rows": [
            ["Börn, 0 - 9 ára","0 kr","",""],
            ["Ungmenni, 10 - 17 ára","400 kr *","1.450 kr","2.000 kr"],
            ["Fullorðnir","1.500 kr","7.000 kr","34.000 kr"],
            ["67 ára og eldri","","","4.000 kr"],
            ["Handhafar TR – Örorkuskírteinis","0 kr","",""]
          ]
        },
        {
          "head": ["Sundföt","Handklæði"],
          "rows": [["Leiga","1.270 kr","860 kr"],["Sund, handklæði og sundföt","2.700 kr",""]]
        },
        {"head":[],"rows":[["Útg. á rafr. handhafakorti","1.000 kr"],["Brautarleiga v. kennslu","8.150 kr"]]}
      ]
    },
    "priceNotes": [
      "* Börn byrja að greiða 1. ágúst árið sem þau verða 10 ára.",
      "** Inneign 10 skipta korta gildir í 4 ár frá kaupum – skiptakort gilda ekki fyrir hópa.",
      "*** 12 mánaðar binding, mánaðargjald er 2.833 kr pr fullorðin og 333 kr fyrir 67 ára og eldri.",
      "Þar sem Reykjavíkurkortið er aðgangskort er framvísun kortsins nauðsynleg til notkunar. Ekki er mögulegt að óska eftir aðgangi með öllum leiðum, s.s. uppflettingu á kennitölu í afgreiðslu nema gegn framvísan löggildra skilríkja. Aðgangskort er forsenda virkni áskrifta/inneigna.",
      "Umönnunaraðili barna fær frítt með gegn framvísun umönnunarskírteinis frá TR."
    ]
  },
  {
    "id": "ylstrondin-nautholsvik",
    "name": "Ylströndin, Nauthólsvík",
    "region": "hofudborgarsvaedid",
    "kind": "lagoon",
    "source": "https://sundlaugar.is/sundlaugasafn/ylstrondin-nautholsvik/",
    "fetched": "2026-09-16",
    "address": "Siglunes",
    "phone": "411 5330",
    "email": "ylstrond@reykjavik.is",
    "web": "https://reykjavik.is/ibuar-ithrottir-tomstundir-menning-og-listir-ithrottir-og-utivist-ylstrondin-i-nautholsvik/afgreidslutimi-ylstrond",
    "facebook": null,
    "instagram": null,
    "longest": null,
    "facilities": ["hotTubs","kids","food"],
    "hours": [
      {
        "kind": "open",
        "title": "Opnunartími, 19. ágúst – 14. maí",
        "season": {"from":"08-19","to":"05-14"},
        "rows": [
          {"label":"Mánudaga","days":[1],"closed":true,"times":[],"extra":null},
          {"label":"Þriðjudaga – föstudaga","days":[2,3,4,5],"closed":false,"times":["11:00–19:00"],"extra":null},
          {"label":"Laugardaga","days":[6],"closed":false,"times":["11:00–16:00"],"extra":null},
          {"label":"Sunnudaga","days":[0],"closed":true,"times":[],"extra":null}
        ],
        "notes": []
      }
    ],
    "prices": {
      "year": "2026",
      "sections": [
        {
          "head": ["Stakt skipti","10 tíma kort","20 tíma kort","6 mán. kort","Árskort"],
          "rows": [["Verð","950 kr","5.900 kr","10.800 kr","12.400 kr","22.700 kr"]]
        },
        {"head":["Handklæði","Sundföt"],"rows":[["Leiga","860 kr","1.270 kr"]]}
      ]
    },
    "priceNotes": []
  }
];
